services:

  # 1. Kafka Broker
  kafka-broker:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"


    environment:
      # KRaft mode
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    networks:
      - data_pipeline

    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

      
  # 2. Kafka Exporter - Extracts Kafka metrics for Prometheus
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    restart: always

    command:
      - "--kafka.server=kafka:9092"
      - "--web.listen-address=:9308"

    ports:
      - "9308:9308"

    depends_on:
      kafka-broker:
        condition: service_healthy

    networks:
      - data_pipeline


# 3. Prometheus - Time-series Database for Metrics Storage
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - kafka-exporter
    networks:
      - data_pipeline


  # 4. Grafana - Visualization Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # Optional: Enable anonymous access to bypass login screen
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      # 1. Automated Prometheus connection (Data Source provisioning)
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      # 2. Automated loading of dashboard provider settings
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # 3. Mount folder containing actual JSON dashboard files
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - data_pipeline
 # 5. postgres - database
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../storage/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - data_pipeline
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  # 6. Producer (Python Ingestion App)
  ingestion_service:
    build:
      context: ..
      dockerfile: services/ingestion_service/Dockerfile
    container_name: ingestion_service
    env_file: ../.env
    restart: on-failure
    depends_on:
      kafka-broker:
        condition: service_healthy
    networks:
      - data_pipeline




networks:
  data_pipeline:
    driver: bridge

volumes:
  postgres_data: